apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  labels:
    app: jmeter-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
      - name: jmeter-master
        image: pedrocesarti/jmeter-docker:latest
        args: ["master"]
        ports:
        - containerPort: 60000
